New Resource: wiz_connector_gcp
AxtonGrams/terraform-provider-wiz pull request #164
Opened 2023-08-17 13:51 UTC by jschoombee

closes #158 

acceptance tests:

```sh
❯ TF_ACC=1 go test ./internal/acceptance/... -v -run='TestAccResourceWizConnectorAws_basic'
=== RUN   TestAccResourceWizConnectorAws_basic
2023/08/17 15:05:17 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:18 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:18 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:19 [DEBUG] POST https://api.eu4.app.wiz.io/graphql
2023/08/17 15:05:19 [DEBUG] POST https://api.eu4.app.wiz.io/graphql
2023/08/17 15:05:20 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:20 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:21 [DEBUG] POST https://api.eu4.app.wiz.io/graphql
2023/08/17 15:05:21 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:22 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:22 [DEBUG] POST https://api.eu4.app.wiz.io/graphql
--- PASS: TestAccResourceWizConnectorAws_basic (5.90s)
PASS
ok      wiz.io/hashicorp/terraform-provider-wiz/internal/acceptance     7.096s
❯ TF_ACC=1 go test ./internal/acceptance/... -v -run='TestAccResourceWizConnectorGcp_basic'
=== RUN   TestAccResourceWizConnectorGcp_basic
2023/08/17 15:05:33 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:34 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:35 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:35 [DEBUG] POST https://api.eu4.app.wiz.io/graphql
2023/08/17 15:05:36 [DEBUG] POST https://api.eu4.app.wiz.io/graphql
2023/08/17 15:05:36 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:37 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:37 [DEBUG] POST https://api.eu4.app.wiz.io/graphql
2023/08/17 15:05:38 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:38 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/08/17 15:05:39 [DEBUG] POST https://api.eu4.app.wiz.io/graphql
--- PASS: TestAccResourceWizConnectorGcp_basic (6.18s)
PASS
ok      wiz.io/hashicorp/terraform-provider-wiz/internal/acceptance     6.470s
```

2023-08-17 15:33 UTC, gramsa49 requested changes

2023-08-17 15:33 UTC, gramsa49 commented on internal/wiz/structs.go
> +	SubscriptionID string `json:"subscriptionId"`
json should be subscriptionID, not subscriptionId

2023-08-17 15:59 UTC, jschoombee commented on internal/wiz/structs.go
> +	DelegateUser                 string                      `json:"delegate_user"`
spotted thanks, so many snake/camel casing inconsistencies with the schema for some reason 🤠

2023-11-13 10:51 UTC, aaronsutton commented
It looks like the requested changes have been made. Is it possible to merge this PR? I'm looking to make use of the wiz connector resource for GCP. Thanks!

2023-12-12 21:20 UTC, gramsa49 approved these changes

2023-12-12 21:21 UTC, merged